a, b = 10, 6
print("{} + {} = {}".format(a, b, a + b))
print(f'{a} - {b} = {a - b}')
print(a * b)
print(a // b)
print(a ^ b)
print(a % b)
print(a > b)
print(a >= b)
print(a <= b)
print(a == b)
print(a & b)
print(a | b)
print(a ^ b)
print(~(a == b))
print(a >> 5)
print(a << 6)
# a = (bin(a)[2:])
print(bin(a)[2:][::-1])